######################################################################################

# Replace all {{ ROLE }} with corresponding role name.

- hosts: "all"
  #user: "defaults to SSH_USER if not specified"
  become: true
  #become_method: "sudo"
  gather_facts: true
  tasks:

    - name: "load vars from corresponding files in vars directory"
      ansible.builtin.include_vars:
        dir: "vars/"
        # If the path is relative, it will look for the file in vars/ subdirectory of a role or relative to playbook.
        #file: "./main.yml"
        extensions:
          - 'yaml'
          - 'yml'
        ignore_unknown_extensions: true
      tags: ["VARS"]

    - name: "Initialize {{ ROLE }} role"
      ansible.builtin.include_role:
        name: "roles/{{ ROLE }}"
        tasks_from: "main"
        apply:
          tags: ["{{ ROLE }}"]
      tags: ["{{ ROLE }}"]
